export const skillData=[
    {
        name:"javascript",
        img:"skills/javascript.png"
    },
    {
        name:"bootstrap",
        img:"skills/bootstrap.png"
    },
    {
        name:"html",
        img:"skills/html.png"
    },
    {
        name:"css",
        img:"skills/css.png"
    },
    {
        name:"php",
        img:"skills/php.png"
    },
    {
        name:"react",
        img:"skills/react.png"
    },
    {
        name:"saas",
        img:"skills/sass.png"
    },
    {
        name:"node",
        img:"skills/node.png"
    },
    {
        name:"express",
        img:"skills/express.png"
    }
]